language: python
sudo: false
cache: pip
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    CFLAGS="-O0"

matrix:
  include:
    - env: TOXENV=check
    - env: TOXENV=3.5
      python: 3.5
    - env: TOXENV=3.6
      python: 3.6
    - env: TOXENV=3.7
      python: 3.7

before_install:
  - sudo apt-get install -y libxml2-dev libxml2-utils
  - cat /etc/os-release

install:
  - pip install tox coveralls
  - virtualenv --version
  - pip --version
  - tox --version

script:
  - tox -v

after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat

after_success:
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: always
