language: python
python:
        - "3.3"
        - "3.4"

install:
        - pip install -r test_requirements.txt

script:
        #- python3 setup.py test -a test
        - coverage run setup.py test

after_success:
        - codecov
